# Generated by Django 2.1.5 on 2019-01-25 13:44

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_teamseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['first_name', 'last_name'])),
                ('height', models.FloatField(help_text='In cm')),
                ('weight', models.FloatField(help_text='In kg')),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
