# Generated by Django 3.1.1 on 2020-09-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='playerinteam',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='teamseason',
            options={'get_latest_by': 'modified'},
        ),
    ]
